use blob_arena::components::stats::{Stats, StatsTrait};

const WEAPON_COUNT: u8 = 43;


#[derive(Copy, Drop, Print, Serde, SerdeLen)]
enum Weapon {
    AlgorithmicAegis,
    ArgentShield,
    Balloons,
    BannerOfAnger,
    BannerOfBrilliance,
    BannerOfDetection,
    BannerOfEnlightenment,
    BannerOfFury,
    BannerOfGiants,
    BannerOfPerfection,
    BannerOfPower,
    BannerOfProtection,
    BannerOfRage,
    BannerOfReflection,
    BannerOfSkill,
    BannerOfTheFox,
    BannerOfTheTwins,
    BannerOfTitans,
    BannerOfTonyHawk,
    BannerOfVitriol,
    Banner,
    Briq,
    Calculator,
    DevvingForTheDistracted,
    DiamondHands,
    DopeUzi,
    GhostWand,
    Grimoire,
    GrugsClub,
    JediswapSaber,
    Katana,
    LordsBanner,
    LsHasNoChill,
    Mandolin,
    SignIso,
    SignatureBanner,
    SithswapSaber,
    Spaghetti,
    Squid,
    StarkMagic,
    StarkShield,
    Stool,
    Warhammer,
}

impl WeaponImpl of StatsTrait<Weapon> {
    fn stats(self: Weapon) -> Stats {
        match self {
            Weapon::AlgorithmicAegis => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::ArgentShield => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::Balloons => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfAnger => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfBrilliance => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfDetection => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfEnlightenment => Stats {
                attack: 0, defense: 0, speed: 0, strength: 0,
            },
            Weapon::BannerOfFury => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfGiants => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfPerfection => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfPower => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfProtection => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfRage => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfReflection => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfSkill => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfTheFox => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfTheTwins => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfTitans => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfTonyHawk => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::BannerOfVitriol => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::Banner => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::Briq => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::Calculator => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::DevvingForTheDistracted => Stats {
                attack: 0, defense: 0, speed: 0, strength: 0,
            },
            Weapon::DiamondHands => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::DopeUzi => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::GhostWand => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::Grimoire => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::GrugsClub => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::JediswapSaber => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::Katana => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::LordsBanner => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::LsHasNoChill => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::Mandolin => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::SignIso => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::SignatureBanner => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::SithswapSaber => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::Spaghetti => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::Squid => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::StarkMagic => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::StarkShield => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::Stool => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
            Weapon::Warhammer => Stats { attack: 0, defense: 0, speed: 0, strength: 0, },
        }
    }
    fn index(self: Weapon) -> u8 {
        match self {
            Weapon::AlgorithmicAegis => 0,
            Weapon::ArgentShield => 1,
            Weapon::Balloons => 2,
            Weapon::BannerOfAnger => 3,
            Weapon::BannerOfBrilliance => 4,
            Weapon::BannerOfDetection => 5,
            Weapon::BannerOfEnlightenment => 6,
            Weapon::BannerOfFury => 7,
            Weapon::BannerOfGiants => 8,
            Weapon::BannerOfPerfection => 9,
            Weapon::BannerOfPower => 10,
            Weapon::BannerOfProtection => 11,
            Weapon::BannerOfRage => 12,
            Weapon::BannerOfReflection => 13,
            Weapon::BannerOfSkill => 14,
            Weapon::BannerOfTheFox => 15,
            Weapon::BannerOfTheTwins => 16,
            Weapon::BannerOfTitans => 17,
            Weapon::BannerOfTonyHawk => 18,
            Weapon::BannerOfVitriol => 19,
            Weapon::Banner => 20,
            Weapon::Briq => 21,
            Weapon::Calculator => 22,
            Weapon::DevvingForTheDistracted => 23,
            Weapon::DiamondHands => 24,
            Weapon::DopeUzi => 25,
            Weapon::GhostWand => 26,
            Weapon::Grimoire => 27,
            Weapon::GrugsClub => 28,
            Weapon::JediswapSaber => 29,
            Weapon::Katana => 30,
            Weapon::LordsBanner => 31,
            Weapon::LsHasNoChill => 32,
            Weapon::Mandolin => 33,
            Weapon::SignIso => 34,
            Weapon::SignatureBanner => 35,
            Weapon::SithswapSaber => 36,
            Weapon::Spaghetti => 37,
            Weapon::Squid => 38,
            Weapon::StarkMagic => 39,
            Weapon::StarkShield => 40,
            Weapon::Stool => 41,
            Weapon::Warhammer => 42,
        }
    }
}

impl U8IntoWeapon of Into<u8, Weapon> {
    fn into(self: u8) -> Weapon {
        match self {
            0 => Weapon::AlgorithmicAegis,
            1 => Weapon::ArgentShield,
            2 => Weapon::Balloons,
            3 => Weapon::BannerOfAnger,
            4 => Weapon::BannerOfBrilliance,
            5 => Weapon::BannerOfDetection,
            6 => Weapon::BannerOfEnlightenment,
            7 => Weapon::BannerOfFury,
            8 => Weapon::BannerOfGiants,
            9 => Weapon::BannerOfPerfection,
            10 => Weapon::BannerOfPower,
            11 => Weapon::BannerOfProtection,
            12 => Weapon::BannerOfRage,
            13 => Weapon::BannerOfReflection,
            14 => Weapon::BannerOfSkill,
            15 => Weapon::BannerOfTheFox,
            16 => Weapon::BannerOfTheTwins,
            17 => Weapon::BannerOfTitans,
            18 => Weapon::BannerOfTonyHawk,
            19 => Weapon::BannerOfVitriol,
            20 => Weapon::Banner,
            21 => Weapon::Briq,
            22 => Weapon::Calculator,
            23 => Weapon::DevvingForTheDistracted,
            24 => Weapon::DiamondHands,
            25 => Weapon::DopeUzi,
            26 => Weapon::GhostWand,
            27 => Weapon::Grimoire,
            28 => Weapon::GrugsClub,
            29 => Weapon::JediswapSaber,
            30 => Weapon::Katana,
            31 => Weapon::LordsBanner,
            32 => Weapon::LsHasNoChill,
            33 => Weapon::Mandolin,
            34 => Weapon::SignIso,
            35 => Weapon::SignatureBanner,
            36 => Weapon::SithswapSaber,
            37 => Weapon::Spaghetti,
            38 => Weapon::Squid,
            39 => Weapon::StarkMagic,
            40 => Weapon::StarkShield,
            41 => Weapon::Stool,
            42 => Weapon::Warhammer,
            _ => panic!("wrong weapon index")
        }
    }
}

impl SU8IntoWeapon of Into<@u8, Weapon> {
    fn into(self: @u8) -> Weapon {
        (*self).into()
    }
}
